Traceback (most recent call last):
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/julieneg/opt/miniconda3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
corr_md_dof=ms_md.series_list[0].correlation(ms_md.series_list[1],method='ttest')
print(corr_md_dof)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[17], line 1[0m
[0;32m----> 1[0m corr_md_dof[38;5;241m=[39mms_md[38;5;241m.[39mseries_list[[38;5;241m0[39m][38;5;241m.[39mcorrelation(ms_md[38;5;241m.[39mseries_list[[38;5;241m1[39m],method[38;5;241m=[39m[38;5;124m'[39m[38;5;124mttest[39m[38;5;124m'[39m)
[1;32m      2[0m [38;5;28mprint[39m(corr_md_dof)

File [0;32m~/Documents/GitHub/Pyleoclim_util/pyleoclim/core/series.py:3552[0m, in [0;36mSeries.correlation[0;34m(self, target_series, alpha, statistic, method, number, timespan, settings, seed, common_time_kwargs, mute_pbar)[0m
[1;32m   3550[0m [38;5;28;01mif[39;00m method [38;5;241m==[39m [38;5;124m'[39m[38;5;124mttest[39m[38;5;124m'[39m:
[1;32m   3551[0m     [38;5;28;01mif[39;00m statistic [38;5;241m==[39m [38;5;124m'[39m[38;5;124mpearsonr[39m[38;5;124m'[39m:
[0;32m-> 3552[0m         stat, signf, pval [38;5;241m=[39m corrutils[38;5;241m.[39mcorr_ttest(ts0[38;5;241m.[39mvalue, ts1[38;5;241m.[39mvalue, alpha[38;5;241m=[39malpha)
[1;32m   3553[0m         signif [38;5;241m=[39m [38;5;28mbool[39m(signf)
[1;32m   3554[0m     [38;5;28;01melse[39;00m:

File [0;32m~/Documents/GitHub/Pyleoclim_util/pyleoclim/utils/correlation.py:234[0m, in [0;36mcorr_ttest[0;34m(y1, y2, alpha)[0m
[1;32m    231[0m Ney2 [38;5;241m=[39m N [38;5;241m*[39m ([38;5;241m1[39m[38;5;241m-[39mg2) [38;5;241m/[39m ([38;5;241m1[39m[38;5;241m+[39mg2)
[1;32m    233[0m Ne [38;5;241m=[39m stats[38;5;241m.[39mmstats[38;5;241m.[39mgmean([Ney1[38;5;241m+[39mNey2])
[0;32m--> 234[0m [38;5;28;01massert[39;00m Ne [38;5;241m>[39m[38;5;241m=[39m [38;5;241m10[39m, [38;5;124m'[39m[38;5;124mToo few effective d.o.f. to apply this method![39m[38;5;124m'[39m
[1;32m    236[0m df [38;5;241m=[39m Ne [38;5;241m-[39m [38;5;241m2[39m
[1;32m    237[0m t [38;5;241m=[39m np[38;5;241m.[39mabs(r) [38;5;241m*[39m np[38;5;241m.[39msqrt(df[38;5;241m/[39m([38;5;241m1[39m[38;5;241m-[39mr[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m))

[0;31mAssertionError[0m: Too few effective d.o.f. to apply this method!

